# Generated by Django 6.1 on 2026-08-21 12:14

import django.db.models.deletion
import feed.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Назва класу')),
                ('grade', models.PositiveSmallIntegerField(default=9, verbose_name='Паралель (цифра)')),
                ('letter', models.CharField(default='А', max_length=3, verbose_name='Літера класу')),
            ],
            options={
                'verbose_name': 'Клас',
                'verbose_name_plural': 'Класи',
                'ordering': ['grade', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва предмету')),
                ('icon', models.CharField(default='📚', help_text='Емодзі для відображення поруч із назвою', max_length=10, verbose_name='Емодзі-іконка')),
                ('color', models.CharField(default='#6366f1', help_text='Колір мітки предмету, наприклад #6366f1', max_length=7, verbose_name='Колір (HEX)')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Тема завдання')),
                ('description', models.TextField(blank=True, verbose_name='Опис / умова завдання')),
                ('is_individual', models.BooleanField(default=False, help_text='Якщо True — завдання для конкретного учня', verbose_name='Індивідуальне завдання')),
                ('student_name', models.CharField(blank=True, help_text="Повне ім'я учня для індивідуального завдання", max_length=200, verbose_name="Ім'я учня")),
                ('link_url', models.URLField(blank=True, help_text='Зовнішнє або внутрішнє посилання на матеріал', verbose_name='Посилання')),
                ('link_label', models.CharField(blank=True, help_text='Текст кнопки/посилання (якщо порожньо — URL)', max_length=200, verbose_name='Підпис посилання')),
                ('status', models.CharField(choices=[('published', '✅ Опубліковано'), ('draft', '📝 Чернетка'), ('scheduled', '⏰ Відкладена публікація'), ('archived', '📦 Архів')], default='draft', max_length=20, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Час відкладеної публікації')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Термін виконання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубліковано')),
                ('duplicated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='feed.assignment', verbose_name='Дубліковано з')),
                ('classes', models.ManyToManyField(blank=True, to='feed.classgroup', verbose_name='Призначено класам')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=feed.models.assignment_upload_path, verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=500, verbose_name='Оригінальна назва файлу')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Завантажено')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='feed.assignment', verbose_name='Завдання')),
            ],
            options={
                'verbose_name': 'Файл завдання',
                'verbose_name_plural': 'Файли завдань',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ вчителя')),
                ('avatar_color', models.CharField(default='#6366f1', max_length=7, verbose_name='Колір аватара')),
                ('classes', models.ManyToManyField(blank=True, to='feed.classgroup', verbose_name='Класи')),
                ('subjects', models.ManyToManyField(blank=True, to='feed.subject', verbose_name='Предмети')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Обліковий запис')),
            ],
            options={
                'verbose_name': 'Вчитель',
                'verbose_name_plural': 'Вчителі',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='feed.teacher', verbose_name='Вчитель'),
        ),
    ]
