# Generated by Django 6.1 on 2026-08-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_classgroup_created_by_subject_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Назва класу'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва предмету'),
        ),
    ]
