# Generated by Django 6.1 on 2026-08-21 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_classgroup_name_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Відео буде вбудовано безпосередньо на сторінці завдання', verbose_name='Посилання на YouTube відео'),
        ),
        migrations.CreateModel(
            name='AssignmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Посилання')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Підпис посилання')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_links', to='feed.assignment', verbose_name='Завдання')),
            ],
        ),
    ]
