# Generated by Django 6.1 on 2026-08-21 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_assignment_youtube_url_assignmentlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentYouTubeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Посилання на YouTube')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Назва / підпис відео')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_links', to='feed.assignment', verbose_name='Завдання')),
            ],
        ),
    ]
