# Generated by Django 6.1 on 2026-08-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_assignmentyoutubelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів'),
        ),
        migrations.CreateModel(
            name='AssignmentViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('session_key', models.CharField(blank=True, max_length=64, verbose_name='Ключ сесії / пристрою')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='Час останнього перегляду')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='feed.assignment', verbose_name='Завдання')),
            ],
            options={
                'verbose_name': 'Лог перегляду завдання',
                'verbose_name_plural': 'Логи переглядів завдань',
                'indexes': [models.Index(fields=['assignment', 'ip_address', 'viewed_at'], name='feed_assign_assignm_281d75_idx'), models.Index(fields=['assignment', 'session_key', 'viewed_at'], name='feed_assign_assignm_ef3d31_idx')],
            },
        ),
    ]
