# Generated by Django 6.1 on 2026-08-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_assignment_views_count_assignmentviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar_image',
            field=models.ImageField(blank=True, help_text='Завантажте квадратне фото або зображення для аватара', null=True, upload_to='teacher_avatars/', verbose_name='Фото аватара'),
        ),
    ]
