# Generated by Django 6.1 on 2026-08-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_teacher_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='unarchived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час розархівації'),
        ),
    ]
